### ISSUE TITLE
Let the callee be configurable instead of depending on `arguments.callee`.

### ISSUE THREAD

**Issue by isiahmeadows** [chaijs/assertion-error#8]
First, it's deprecated and considered legacy. Second, not all callers may necessarily call it at the top level, so you can end the stack traces at the API boundary.

**Comment by meeber** [comment]
`arguments.callee` references the currently executing function. I'm not sure why it was `arguments.callee` instead of `AssertionError` in the first place; that line is from 2013, well before my time here.

Anyway, the `AssertionError` function is merely the default starting point to remove frames from the stack trace. It can already be overridden by passing a function as the `ssf` parameter.

**Comment by isiahmeadows** [comment]
Okay. Thanks! (I crossed up `arguments.caller` with `arguments.callee`. Haven't dealt with those in a while.)
